"""Add unique constraint to add_on_rates

Revision ID: 67b973da6292
Revises: 872f94033eb3
Create Date: 2025-12-12 14:38:22.019621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67b973da6292'
down_revision: Union[str, None] = '872f94033eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_add_on_rates_composite', 'add_on_rates', ['add_on_id', 'product_id', 'occupancy_type', 'si_min', 'si_max'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_add_on_rates_composite', 'add_on_rates', type_='unique')
    # ### end Alembic commands ###
