"""update_bsus_rates_to_use_occupancy_id

Revision ID: 69461828dc46
Revises: b375605b8b20
Create Date: 2025-12-11 23:57:19.871901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69461828dc46'
down_revision: Union[str, None] = 'b375605b8b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bsus_rates', sa.Column('occupancy_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_bsus_rates_occupancy_eq', 'bsus_rates', ['occupancy_id', 'eq_zone'])
    op.create_foreign_key(None, 'bsus_rates', 'occupancies', ['occupancy_id'], ['id'])
    op.drop_column('bsus_rates', 'occupancy_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bsus_rates', sa.Column('occupancy_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bsus_rates', type_='foreignkey')
    op.drop_constraint('uq_bsus_rates_occupancy_eq', 'bsus_rates', type_='unique')
    op.drop_column('bsus_rates', 'occupancy_id')
    # ### end Alembic commands ###
