"""really_add_allow_addons_column

Revision ID: 765be293bc72
Revises: dd4e166d523c
Create Date: 2025-12-14 11:26:29.267517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '765be293bc72'
down_revision: Union[str, None] = 'dd4e166d523c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occupancies', sa.Column('allow_addons', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('occupancies', 'allow_addons')
    # ### end Alembic commands ###
