"""create_lob_product_generic_tables

Revision ID: b375605b8b20
Revises: f00fa280a454
Create Date: 2025-12-11 22:46:36.496524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b375605b8b20'
down_revision: Union[str, None] = 'f00fa280a454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lob_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lob_code', sa.String(), nullable=False),
    sa.Column('lob_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lob_master_id'), 'lob_master', ['id'], unique=False)
    op.create_index(op.f('ix_lob_master_lob_code'), 'lob_master', ['lob_code'], unique=True)
    op.create_table('product_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lob_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lob_id'], ['lob_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lob_id', 'product_code', name='uq_product_master_lob_product')
    )
    op.create_index(op.f('ix_product_master_id'), 'product_master', ['id'], unique=False)
    op.create_index(op.f('ix_product_master_product_code'), 'product_master', ['product_code'], unique=False)
    op.create_table('generic_rate_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('rate_key', sa.String(), nullable=False),
    sa.Column('rate_value', sa.Numeric(), nullable=False),
    sa.Column('rate_type', sa.String(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('si_min', sa.Numeric(), nullable=True),
    sa.Column('si_max', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'rate_key', 'si_min', 'si_max', name='uq_generic_rate_product_key_si')
    )
    op.create_index(op.f('ix_generic_rate_tables_id'), 'generic_rate_tables', ['id'], unique=False)
    op.create_index(op.f('ix_add_on_master_id'), 'add_on_master', ['id'], unique=False)
    op.add_column('add_on_product_map', sa.Column('product_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_add_on_product_map_addon_product'), 'add_on_product_map', type_='unique')
    op.create_index(op.f('ix_add_on_product_map_id'), 'add_on_product_map', ['id'], unique=False)
    op.create_foreign_key(None, 'add_on_product_map', 'product_master', ['product_id'], ['id'])
    op.add_column('add_on_rates', sa.Column('product_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_add_on_rates_composite'), 'add_on_rates', type_='unique')
    op.create_index(op.f('ix_add_on_rates_id'), 'add_on_rates', ['id'], unique=False)
    op.create_foreign_key(None, 'add_on_rates', 'product_master', ['product_id'], ['id'])
    op.add_column('bsus_rates', sa.Column('product_code', sa.String(length=20), nullable=True))
    op.add_column('bsus_rates', sa.Column('product_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_bsus_rates_occupancy_eq'), 'bsus_rates', type_='unique')
    op.create_index(op.f('ix_bsus_rates_id'), 'bsus_rates', ['id'], unique=False)
    op.create_foreign_key(None, 'bsus_rates', 'product_master', ['product_id'], ['id'])
    op.add_column('eq_rates', sa.Column('product_code', sa.String(length=20), nullable=True))
    op.add_column('eq_rates', sa.Column('product_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_eq_rates_occupancy_zone'), 'eq_rates', type_='unique')
    op.create_index(op.f('ix_eq_rates_id'), 'eq_rates', ['id'], unique=False)
    op.create_foreign_key(None, 'eq_rates', 'product_master', ['product_id'], ['id'])
    op.create_index(op.f('ix_occupancies_id'), 'occupancies', ['id'], unique=False)
    op.add_column('product_basic_rates', sa.Column('product_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_product_basic_rates_product_occupancy'), 'product_basic_rates', type_='unique')
    op.create_index(op.f('ix_product_basic_rates_id'), 'product_basic_rates', ['id'], unique=False)
    op.create_foreign_key(None, 'product_basic_rates', 'product_master', ['product_id'], ['id'])
    op.add_column('stfi_rates', sa.Column('product_code', sa.String(length=20), nullable=True))
    op.add_column('stfi_rates', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stfi_rates_id'), 'stfi_rates', ['id'], unique=False)
    op.create_foreign_key(None, 'stfi_rates', 'product_master', ['product_id'], ['id'])
    op.add_column('terrorism_slabs', sa.Column('product_code', sa.String(length=20), nullable=True))
    op.add_column('terrorism_slabs', sa.Column('product_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_terrorism_slabs_type_range'), 'terrorism_slabs', type_='unique')
    op.create_index(op.f('ix_terrorism_slabs_id'), 'terrorism_slabs', ['id'], unique=False)
    op.create_foreign_key(None, 'terrorism_slabs', 'product_master', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'terrorism_slabs', type_='foreignkey')
    op.drop_index(op.f('ix_terrorism_slabs_id'), table_name='terrorism_slabs')
    op.create_unique_constraint(op.f('uq_terrorism_slabs_type_range'), 'terrorism_slabs', ['occupancy_type', 'si_min', 'si_max'], postgresql_nulls_not_distinct=False)
    op.drop_column('terrorism_slabs', 'product_id')
    op.drop_column('terrorism_slabs', 'product_code')
    op.drop_constraint(None, 'stfi_rates', type_='foreignkey')
    op.drop_index(op.f('ix_stfi_rates_id'), table_name='stfi_rates')
    op.drop_column('stfi_rates', 'product_id')
    op.drop_column('stfi_rates', 'product_code')
    op.drop_constraint(None, 'product_basic_rates', type_='foreignkey')
    op.drop_index(op.f('ix_product_basic_rates_id'), table_name='product_basic_rates')
    op.create_unique_constraint(op.f('uq_product_basic_rates_product_occupancy'), 'product_basic_rates', ['product_code', 'occupancy_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('product_basic_rates', 'product_id')
    op.drop_index(op.f('ix_occupancies_id'), table_name='occupancies')
    op.drop_constraint(None, 'eq_rates', type_='foreignkey')
    op.drop_index(op.f('ix_eq_rates_id'), table_name='eq_rates')
    op.create_unique_constraint(op.f('uq_eq_rates_occupancy_zone'), 'eq_rates', ['occupancy_id', 'eq_zone'], postgresql_nulls_not_distinct=False)
    op.drop_column('eq_rates', 'product_id')
    op.drop_column('eq_rates', 'product_code')
    op.drop_constraint(None, 'bsus_rates', type_='foreignkey')
    op.drop_index(op.f('ix_bsus_rates_id'), table_name='bsus_rates')
    op.create_unique_constraint(op.f('uq_bsus_rates_occupancy_eq'), 'bsus_rates', ['occupancy_type', 'eq_zone'], postgresql_nulls_not_distinct=False)
    op.drop_column('bsus_rates', 'product_id')
    op.drop_column('bsus_rates', 'product_code')
    op.drop_constraint(None, 'add_on_rates', type_='foreignkey')
    op.drop_index(op.f('ix_add_on_rates_id'), table_name='add_on_rates')
    op.create_unique_constraint(op.f('uq_add_on_rates_composite'), 'add_on_rates', ['add_on_id', 'product_code', 'occupancy_type', 'si_min', 'si_max'], postgresql_nulls_not_distinct=False)
    op.drop_column('add_on_rates', 'product_id')
    op.drop_constraint(None, 'add_on_product_map', type_='foreignkey')
    op.drop_index(op.f('ix_add_on_product_map_id'), table_name='add_on_product_map')
    op.create_unique_constraint(op.f('uq_add_on_product_map_addon_product'), 'add_on_product_map', ['add_on_id', 'product_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('add_on_product_map', 'product_id')
    op.drop_index(op.f('ix_add_on_master_id'), table_name='add_on_master')
    op.drop_index(op.f('ix_generic_rate_tables_id'), table_name='generic_rate_tables')
    op.drop_table('generic_rate_tables')
    op.drop_index(op.f('ix_product_master_product_code'), table_name='product_master')
    op.drop_index(op.f('ix_product_master_id'), table_name='product_master')
    op.drop_table('product_master')
    op.drop_index(op.f('ix_lob_master_lob_code'), table_name='lob_master')
    op.drop_index(op.f('ix_lob_master_id'), table_name='lob_master')
    op.drop_table('lob_master')
    # ### end Alembic commands ###
