"""Sync database schema

Revision ID: db53f0e5f521
Revises: 
Create Date: 2025-12-11 01:05:08.591162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db53f0e5f521'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('terrorism_slabs')
    op.drop_table('fire_occupancy_master')
    op.drop_table('addon_product_map')
    op.drop_table('terrorism_slab_breakup')
    op.drop_table('product_rates')
    op.drop_table('fire_base_rates')
    op.drop_table('product_master')
    op.drop_table('addon_master')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addon_master',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('addon_master_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('addon_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('addon_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='addon_master_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('product_master',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('terrorism_applicable', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('product_master_pkey')),
    sa.UniqueConstraint('product_code', name=op.f('product_master_product_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('fire_base_rates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('iib_occupancy_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('product', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('basic_rate', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('stfi_rate', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('zone_iv', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('zone_iii', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('zone_ii', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('zone_i', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('terrorism_rate', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('fire_base_rates_pkey'))
    )
    op.create_table('product_rates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('basic_rate', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=False),
    sa.Column('terrorism_rate', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('product_rates_pkey')),
    sa.UniqueConstraint('product_code', name=op.f('product_rates_product_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('terrorism_slab_breakup',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('slab_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('balance_rate_non_ind', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('balance_rate_ind', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('terrorism_slab_breakup_pkey'))
    )
    op.create_table('addon_product_map',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('addon_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['addon_master.id'], name=op.f('addon_product_map_addon_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('addon_product_map_pkey'))
    )
    op.create_table('fire_occupancy_master',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('iib_occupancy_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('section_aift', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('extra_meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('fire_occupancy_master_pkey')),
    sa.UniqueConstraint('iib_occupancy_code', name=op.f('fire_occupancy_master_iib_occupancy_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('terrorism_slabs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('slab_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('si_min', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('si_max', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('rate_non_ind', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('rate_ind', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=True),
    sa.Column('loss_limit', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('terrorism_slabs_pkey'))
    )
    # ### end Alembic commands ###
