"""add_allow_addons_to_occupancies

Revision ID: dd4e166d523c
Revises: a100416aa0e0
Create Date: 2025-12-14 10:18:36.466529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd4e166d523c'
down_revision: Union[str, None] = 'a100416aa0e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_add_on_rates_composite', 'add_on_rates', ['add_on_id', 'product_id', 'occupancy_type', 'si_min', 'si_max'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_add_on_rates_composite', 'add_on_rates', type_='unique')
    # ### end Alembic commands ###
