import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { RatingResponseData } from '../../api/ratingApi';

// Extend jsPDF types for autotable
interface JsPDFWithAutoTable extends jsPDF {
    lastAutoTable: { finalY: number };
}

export interface PolicySummaryData {
    customerName: string;
    address: string;
    policyType: string; // e.g., "Bharat Griha Raksha"
    occupancy: string;
    periodYears: number;

    // Financials
    siData: {
        building: number;
        contents: number;
        addons: Record<string, number>;
    };

    premiumData: RatingResponseData;
}

/**
 * Generates a PDF Policy Summary
 */
export const generatePolicySummaryPDF = (data: PolicySummaryData) => {
    const doc = new jsPDF() as JsPDFWithAutoTable;
    const { customerName, address, policyType, occupancy, periodYears, siData, premiumData } = data;

    // --- Header ---
    doc.setFontSize(22);
    doc.setTextColor(40, 60, 100);
    doc.text("iRiskAssist360", 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Premium Quotation Summary", 14, 26);

    doc.setLineWidth(0.5);
    doc.setDrawColor(200);
    doc.line(14, 30, 196, 30);

    // --- Customer Info ---
    let y = 40;
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text(`Proposer: ${customerName}`, 14, y);
    y += 6;
    doc.setFontSize(10);
    doc.text(`Address: ${address}`, 14, y);
    y += 10;

    // --- Policy Details Grid (Manual Layout or Table) ---
    autoTable(doc, {
        startY: y,
        head: [['Product', 'Occupancy', 'Tenure (Years)']],
        body: [[policyType, occupancy, periodYears.toString()]],
        theme: 'plain',
        styles: { fontSize: 10, cellPadding: 2 },
        headStyles: { fontStyle: 'bold' }
    });

    y = doc.lastAutoTable.finalY + 10;

    // --- Sum Insured Section ---
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Sum Insured Breakdown", 14, y);
    y += 5;

    const siRows = [
        ['Building', siData.building.toLocaleString('en-IN')],
        ['Contents', siData.contents.toLocaleString('en-IN')]
    ];
    Object.entries(siData.addons).forEach(([k, v]) => {
        siRows.push([k, v.toLocaleString('en-IN')]);
    });
    const totalSI = siData.building + siData.contents + Object.values(siData.addons).reduce((a, b) => a + b, 0);
    siRows.push(['Total Sum Insured', totalSI.toLocaleString('en-IN')]);

    autoTable(doc, {
        startY: y,
        head: [['Component', 'Amount (INR)']],
        body: siRows,
        theme: 'grid',
        headStyles: { fillColor: [41, 128, 185], textColor: 255 },
        columnStyles: { 1: { halign: 'right' } }
    });

    y = doc.lastAutoTable.finalY + 10;

    // --- Premium Section ---
    doc.text("Premium Calculation", 14, y);
    y += 5;

    const b = premiumData.breakdown;
    const pRows = [
        ['Base Premium', b.base?.toFixed(2) || b.firePremium?.toFixed(2) || '0.00'],
        ['Terrorism Premium', b.terrorismPremium?.toFixed(2) || '0.00'],
    ];

    // Add-ons
    const visited = ['base', 'firePremium', 'terrorismPremium', 'gst', 'loadings', 'discounts', 'paPremium'];
    if (b.paPremium) pRows.push(['P.A. Cover', b.paPremium.toFixed(2)]);

    Object.entries(b).forEach(([k, v]) => {
        if (!visited.includes(k) && typeof v === 'number') {
            pRows.push([k.replace(/_/g, ' '), v.toFixed(2)]);
        }
    });

    if (premiumData.breakdown.loadings) {
        pRows.push(['Loadings (+)', premiumData.breakdown.loadings.toFixed(2)]);
    }
    if (premiumData.breakdown.discounts) {
        pRows.push(['Discounts (-)', premiumData.breakdown.discounts.toFixed(2)]);
    }

    pRows.push(['Net Premium', premiumData.net_premium?.toFixed(2) || premiumData.netPremium?.toFixed(2) || '0.00']);
    pRows.push(['GST (18%)', premiumData.gst.toFixed(2)]);

    // Gross Row
    const gross = premiumData.gross_premium || premiumData.total_premium || 0;

    autoTable(doc, {
        startY: y,
        head: [['Description', 'Premium (INR)']],
        body: pRows,
        theme: 'striped',
        headStyles: { fillColor: [50, 50, 50] },
        columnStyles: { 1: { halign: 'right' } },
        foot: [['TOTAL PAYABLE', gross.toFixed(2)]],
        footStyles: { fillColor: [22, 160, 133], textColor: 255, fontStyle: 'bold', halign: 'right' }
    });

    // --- Footer ---
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Generated by iRiskAssist360 on ${new Date().toLocaleString()}`, 14, pageHeight - 10);

    // Save
    doc.save(`Quote_${customerName.replace(/\s+/g, '_')}_${Date.now()}.pdf`);
};
